name: Update V2Ray Sub

on:
  schedule:
    - cron: '0 * * * *'  # هر یک ساعت راس دقیقه 00 اجرا می‌شود
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository 🛎️
        uses: actions/checkout@v3

      - name: Install Xray Core (Direct & Fast) ⚡
        run: |
          curl -sL https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip -o xray.zip
          sudo unzip -o xray.zip xray -d /usr/local/bin/
          sudo chmod +x /usr/local/bin/xray
          rm -f xray.zip
          xray version



      - name: Set up Python 🐍
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies 📦
        run: |
          pip install requests

      - name: Prepare Folders and Files 📄
        run: |
          mkdir -p protocols countries
          touch sub.txt

      - name: Run Modular Scraper Engine 👾
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHANNEL: ${{ secrets.TELEGRAM_CHANNEL }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHANNEL_ID: ${{ secrets.TG_CHANNEL_ID }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          # رفتن به پوشه اصلی و اجرای بیلدر
          python scripts/build.py

      - name: Commit and push changes 🚀
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add top100.txt top10.txt sub.txt protocols/ countries/
          git diff --staged --quiet || (git commit -m "🤖 Auto-update modular configs: $(date +'%Y-%m-%d %H:%M')" && git push)
