name: Update V2Ray Sub

on:
  schedule:
    # هر ۶ ساعت یک‌بار اجرا شود
    - cron: '0 */6 * * *'
  workflow_dispatch: # دکمه اجرای دستی

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository 🛎️
        uses: actions/checkout@v3

      - name: Set up Python 🐍
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies 📦
        run: |
          pip install requests

      # ایجاد پیشاپیش فایل و پوشه‌ها برای جلوگیری از بهانه‌گیری Git
      - name: Prepare Folders and Files 📄
        run: |
          mkdir -p protocols countries
          touch sub.txt

      - name: Run Scraper 👾
        run: |
          python scraper.py

      - name: Commit and Push 🚀
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # اضافه کردن تمام تغییرات (فایل اصلی + پوشه‌های کشور و پروتکل)
          git add sub.txt protocols/ countries/
          
          # کامیت تنها در صورت وجود تفاوت واقعی
          git diff --staged --quiet || (git commit -m "🤖 Auto-update & categorize configs: $(date +'%Y-%m-%d %H:%M')" && git push)
